"""Shared H800 MLA vLLM live-probe fixture rows for unit tests."""

from __future__ import annotations

from typing import Any


_BASE_META: dict[str, Any] = {
    "attention_backend": "FLASHINFER_MLA",
    "use_mla": True,
    "runtime_num_kv_heads": 1,
    "runtime_head_size": 576,
    "kv_lora_rank": 512,
    "qk_nope_head_dim": 128,
    "qk_rope_head_dim": 64,
    "qk_head_dim": 192,
    "v_head_dim": 128,
    "block_size": 64,
    "kv_cache_dtype": "auto",
    "calculate_kv_scales": False,
    "attn_module_sliding_window": None,
    "alibi_slopes": None,
    "logits_soft_cap": None,
    "attn_type": "decoder",
    "n_q_head": 128,
}


def _mla_row(
    *,
    batch_id: int,
    scope: str,
    cuda_time_ms: float,
    batch_size: int,
    batch_num_tokens: int,
    batch_num_prefill_tokens: int,
    batch_num_decode_tokens: int,
    batch_request_num_tokens: list[int],
    max_seqlen_q: int,
    max_seqlen_k: int,
    num_actual_tokens: int,
) -> dict[str, Any]:
    return {
        "batch_id": batch_id,
        "batch_size": batch_size,
        "batch_num_tokens": batch_num_tokens,
        "batch_num_prefill_tokens": batch_num_prefill_tokens,
        "batch_num_decode_tokens": batch_num_decode_tokens,
        "batch_request_num_tokens": list(batch_request_num_tokens),
        "op_name": scope,
        "cuda_time_ms": cuda_time_ms,
        "count": 1,
        "meta": {
            **_BASE_META,
            "max_seqlen_q": max_seqlen_q,
            "max_seqlen_k": max_seqlen_k,
            "num_actual_tokens": num_actual_tokens,
        },
    }


def h800_mla_mixed_rows() -> list[dict[str, Any]]:
    """Return the 13 real-shape H800 MLA rows from the 2026-06-27 probe."""

    return [
        # Batch 0: prefill-only.
        _mla_row(
            batch_id=0,
            scope="attn_mla_kv_cache_save",
            cuda_time_ms=0.002529,
            batch_size=1,
            batch_num_tokens=64,
            batch_num_prefill_tokens=64,
            batch_num_decode_tokens=0,
            batch_request_num_tokens=[64],
            max_seqlen_q=64,
            max_seqlen_k=64,
            num_actual_tokens=64,
        ),
        _mla_row(
            batch_id=0,
            scope="attn_mla_prefill_kv_up_proj",
            cuda_time_ms=0.016928,
            batch_size=1,
            batch_num_tokens=64,
            batch_num_prefill_tokens=64,
            batch_num_decode_tokens=0,
            batch_request_num_tokens=[64],
            max_seqlen_q=64,
            max_seqlen_k=64,
            num_actual_tokens=64,
        ),
        _mla_row(
            batch_id=0,
            scope="attn_mla_prefill",
            cuda_time_ms=0.013022,
            batch_size=1,
            batch_num_tokens=64,
            batch_num_prefill_tokens=64,
            batch_num_decode_tokens=0,
            batch_request_num_tokens=[64],
            max_seqlen_q=64,
            max_seqlen_k=64,
            num_actual_tokens=64,
        ),
        # Batch 1: mixed prefill + decode.
        _mla_row(
            batch_id=1,
            scope="attn_mla_kv_cache_save",
            cuda_time_ms=0.002528,
            batch_size=2,
            batch_num_tokens=65,
            batch_num_prefill_tokens=64,
            batch_num_decode_tokens=1,
            batch_request_num_tokens=[1, 64],
            max_seqlen_q=64,
            max_seqlen_k=65,
            num_actual_tokens=65,
        ),
        _mla_row(
            batch_id=1,
            scope="attn_mla_prefill_kv_up_proj",
            cuda_time_ms=0.016256,
            batch_size=2,
            batch_num_tokens=65,
            batch_num_prefill_tokens=64,
            batch_num_decode_tokens=1,
            batch_request_num_tokens=[1, 64],
            max_seqlen_q=64,
            max_seqlen_k=65,
            num_actual_tokens=64,
        ),
        _mla_row(
            batch_id=1,
            scope="attn_mla_prefill",
            cuda_time_ms=0.013185,
            batch_size=2,
            batch_num_tokens=65,
            batch_num_prefill_tokens=64,
            batch_num_decode_tokens=1,
            batch_request_num_tokens=[1, 64],
            max_seqlen_q=64,
            max_seqlen_k=65,
            num_actual_tokens=64,
        ),
        _mla_row(
            batch_id=1,
            scope="attn_mla_decode_q_latent_proj",
            cuda_time_ms=0.006432,
            batch_size=2,
            batch_num_tokens=65,
            batch_num_prefill_tokens=64,
            batch_num_decode_tokens=1,
            batch_request_num_tokens=[1, 64],
            max_seqlen_q=1,
            max_seqlen_k=65,
            num_actual_tokens=1,
        ),
        _mla_row(
            batch_id=1,
            scope="attn_mla_decode",
            cuda_time_ms=0.069984,
            batch_size=2,
            batch_num_tokens=65,
            batch_num_prefill_tokens=64,
            batch_num_decode_tokens=1,
            batch_request_num_tokens=[1, 64],
            max_seqlen_q=1,
            max_seqlen_k=65,
            num_actual_tokens=1,
        ),
        _mla_row(
            batch_id=1,
            scope="attn_mla_v_up_proj",
            cuda_time_ms=0.011840,
            batch_size=2,
            batch_num_tokens=65,
            batch_num_prefill_tokens=64,
            batch_num_decode_tokens=1,
            batch_request_num_tokens=[1, 64],
            max_seqlen_q=1,
            max_seqlen_k=65,
            num_actual_tokens=1,
        ),
        # Batch 2: decode-only.
        _mla_row(
            batch_id=2,
            scope="attn_mla_kv_cache_save",
            cuda_time_ms=0.002304,
            batch_size=1,
            batch_num_tokens=1,
            batch_num_prefill_tokens=0,
            batch_num_decode_tokens=1,
            batch_request_num_tokens=[1],
            max_seqlen_q=1,
            max_seqlen_k=65,
            num_actual_tokens=1,
        ),
        _mla_row(
            batch_id=2,
            scope="attn_mla_decode_q_latent_proj",
            cuda_time_ms=0.008513,
            batch_size=1,
            batch_num_tokens=1,
            batch_num_prefill_tokens=0,
            batch_num_decode_tokens=1,
            batch_request_num_tokens=[1],
            max_seqlen_q=1,
            max_seqlen_k=65,
            num_actual_tokens=1,
        ),
        _mla_row(
            batch_id=2,
            scope="attn_mla_decode",
            cuda_time_ms=0.067647,
            batch_size=1,
            batch_num_tokens=1,
            batch_num_prefill_tokens=0,
            batch_num_decode_tokens=1,
            batch_request_num_tokens=[1],
            max_seqlen_q=1,
            max_seqlen_k=65,
            num_actual_tokens=1,
        ),
        _mla_row(
            batch_id=2,
            scope="attn_mla_v_up_proj",
            cuda_time_ms=0.009984,
            batch_size=1,
            batch_num_tokens=1,
            batch_num_prefill_tokens=0,
            batch_num_decode_tokens=1,
            batch_request_num_tokens=[1],
            max_seqlen_q=1,
            max_seqlen_k=65,
            num_actual_tokens=1,
        ),
    ]


H800_MIXED_BATCH1_TIMES_MS: dict[str, float] = {
    "attn_mla_kv_cache_save": 0.002528,
    "attn_mla_prefill_kv_up_proj": 0.016256,
    "attn_mla_prefill": 0.013185,
    "attn_mla_decode_q_latent_proj": 0.006432,
    "attn_mla_decode": 0.069984,
    "attn_mla_v_up_proj": 0.011840,
}
